services:

  database:
    image: postgres
    environment:
      - POSTGRES_USER=django_project
      - POSTGRES_PASSWORD=django_project
    restart: "no"

  site:
    build: .
    command: bash /django_project/server/django-devserver.sh
    depends_on:
    - database
    ports:
    - "8000:8000"
    environment:
      FQDN: 0.0.0.0
      DB_HOST: database
      PYTHONUNBUFFERED: 1
    restart: "no"


version: '2'