services:

  site:
    build: .
    environment:
      FQDN: 0.0.0.0
      DB_HOST: database
      PYTHONUNBUFFERED: 1
      SECRET_KEY: "development-only-secret-key"
    ports:
    - "8000:8000"
    restart: "no"

  database:
    image: postgres
    environment:
      POSTGRES_USER: django_project
      POSTGRES_PASSWORD: django_project
    restart: "no"


version: '2'