services:

  site:
    build: .
    environment:
      DB_HOST: database
      PYTHONUNBUFFERED: 1
      SECRET_KEY: "development-only-secret-key"
      FQDN: 0.0.0.0
      SOCIAL_AUTH_FACEBOOK_KEY: ""
      SOCIAL_AUTH_FACEBOOK_SECRET: ""
    restart: "no"

  database:
    image: postgres
    environment:
      POSTGRES_USER: django_project
      POSTGRES_PASSWORD: django_project
    restart: "no"

  proxy:
    build: project_template/server/proxy
    environment:
      FQDN: 0.0.0.0
      CONTACT_EMAIL: self_signed
    ports:
      - "80:80"
      - "443:443"
    restart: "no"


version: '2'