services:

  site:
    build:
      context: server
    environment:
      DB_HOST: database
      PYTHONUNBUFFERED: 1
      EMAIL_HOST: ""
      EMAIL_HOST_PORT: 587
      EMAIL_HOST_USER: ""
      EMAIL_HOST_PASSWORD: ""
      EMAIL_USE_TLS: 1
    logging:
      options:
        max-size: "10m"
        max-file: "30"
    restart: "unless-stopped"

  database:
    image: postgres
    environment:
      POSTGRES_USER: {{ project_name }}
      POSTGRES_PASSWORD: {{ project_name }}
    logging:
      options:
        max-size: "10m"
        max-file: "30"
    restart: "unless-stopped"


version: '2'
