services:

  site:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: {{ project_name }}.settings.dev
      FQDN: 0.0.0.0
      FACEBOOK_KEY: ""
      FACEBOOK_SECRET: ""
    volumes:
      - .:/{{ project_name }}
    command: bash /{{ project_name }}/server/uwsgi.sh --py-autoreload=1
    restart: "no"

  database:
    volumes:
      - ./server/dev/data/:/var/lib/postgresql/data/
    restart: "no"

  proxy:
    environment:
      FQDN: 0.0.0.0
      CONTACT_EMAIL: self_signed
    ports:
      - "80:80"
      - "443:443"
    restart: "no"


version: '2'
