services:

  site:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: {{ project_name }}.settings.dev
      FQDN: 0.0.0.0
      SOCIAL_AUTH_FACEBOOK_KEY: ""
      SOCIAL_AUTH_FACEBOOK_SECRET: ""
    volumes:
      - .:/{{ project_name }}
    restart: "no"

  database:
    volumes:
      - ./server/dev/data/:/var/lib/postgresql/data/
    restart: "no"

  proxy:
    environment:
      FQDN: 0.0.0.0
      CONTACT_EMAIL: self_signed
    restart: "no"


version: '2'
