services:

  site:
    build: .
    command: bash /{{ project_name }}/server/django-devserver.sh
    environment:
      DJANGO_SETTINGS_MODULE: {{ project_name }}.settings.dev
      FQDN: 0.0.0.0
    volumes:
      - .:/{{ project_name }}
    ports:
      - "8000:8000"
    restart: "no"

  database:
    volumes:
      - ./server/dev/data/:/var/lib/postgresql/data/
    restart: "no"


version: '2'
