services:

  site:
    build:
      args:
        REPO_URL:  # TODO
        BRANCH: production
    environment:
      DJANGO_SETTINGS_MODULE: {{ project_name }}.settings.production
      SCHEMA: https
      FQDN: {{ project_name }}.TODO
      FACEBOOK_KEY: ""
      FACEBOOK_SECRET: ""
    volumes:
      - /var/{{ project_name }}/production/site/:/var/media/{{ project_name }}/

  database:
    volumes:
      - /var/{{ project_name }}/production/database/:/var/lib/postgresql/data/

  proxy:
    environment:
      FQDN:  # TODO
      CONTACT_EMAIL:  # TODO
    volumes:
      - /var/{{ project_name }}/production/proxy/:/root/.caddy/acme/


version: '2'
